# version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: authors-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  grpc-server:
    build: .
    container_name: authors-grpc
    restart: always
    ports:
      - "50052:50052"
    environment:
      PORT: 50052
      MONGO_URI: mongodb://mongo:27017/Author-gRPC
    depends_on:
      - mongo

volumes:
  mongo-data:
